[project]
name = "suaia-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "alqudude16", email = "alqudusl358@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "mediapipe>=1.0.1",
    "opencv-python>=5.0.0.93",
    "pygame>=2.6.1",
]

[project.scripts]
suaia-game = "suaia_game:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
